/* Progressive presentation only: authentication and business operations remain in their existing modules. */
(() => {
  document.querySelectorAll('input[type=password]').forEach(input => {
    const wrapper=document.createElement('div');wrapper.className='entry-password';
    input.parentNode.insertBefore(wrapper,input);wrapper.append(input);
    const button=document.createElement('button');button.type='button';button.className='password-toggle';button.textContent='Mostrar';button.setAttribute('aria-controls',input.id);button.setAttribute('aria-label','Mostrar '+(input.labels?.[0]?.textContent.trim().toLowerCase()||'contraseña'));button.setAttribute('aria-pressed','false');
    button.addEventListener('click',()=>{const show=input.type==='password';input.type=show?'text':'password';button.textContent=show?'Ocultar':'Mostrar';button.setAttribute('aria-pressed',String(show));button.setAttribute('aria-label',(show?'Ocultar ':'Mostrar ')+(input.labels?.[0]?.textContent.trim().toLowerCase()||'contraseña'));});wrapper.append(button);
  });
  const steps=[...document.querySelectorAll('.step')];
  if(!steps.length)return;
  document.querySelectorAll('.field').forEach(field=>{const label=field.querySelector('label'),input=field.querySelector('input:not([type=radio]),select,textarea');if(label&&input?.id&&!label.htmlFor)label.htmlFor=input.id;});
  const labels=['Tu restaurante','Información de contacto','Sistema de reservas','Horarios y reglas','Revisión final','Configuración completada'];
  let previous=-1;
  function sync(){const active=steps.findIndex(step=>step.classList.contains('active'));if(active<0||active===previous)return;const initial=previous<0;previous=active;const caption=document.getElementById('entryStepCaption');caption.textContent=active<5?`Paso ${active+1} de 5 · ${labels[active]}`:labels[active];document.querySelectorAll('.entry-steps li').forEach((item,i)=>{item.classList.toggle('done',i<active);if(i===active)item.setAttribute('aria-current','step');else item.removeAttribute('aria-current');});if(!initial){const heading=steps[active].querySelector('h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});heading.scrollIntoView({block:'start',behavior:'auto'});}}}
  new MutationObserver(sync).observe(document.getElementById('onboardingContainer'),{attributes:true,attributeFilter:['class'],subtree:true});sync();
})();
(() => {
 const demo=document.querySelector('.entry-illustration');if(!demo)return;demo.removeAttribute('aria-hidden');demo.setAttribute('role','region');demo.setAttribute('aria-label','Demostración ilustrativa de la atención');
 const scenes=[['TU CLIENTE','Una mesa para cuatro, por favor.','El cliente inicia la consulta por un canal conectado.'],['TU ASISTENTE','Consulto la disponibilidad en tu agenda.','Se utiliza tu programa compatible o el motor incluido.'],['RESPUESTA · EJEMPLO','La reserva se confirma cuando el sistema la acepta.','Las preferencias de zona, ocasión o privacidad se solicitan y comprueban.']];let current=0,timer;const controls=document.createElement('div');controls.className='entry-demo-controls';controls.innerHTML='<div class="demo-caption" role="status">Ejemplo ilustrativo · 1 / 3</div><div><button type="button" aria-label="Escena anterior">←</button><button type="button" aria-label="Reproducir demostración">Reproducir</button><button type="button" aria-label="Escena siguiente">→</button></div>';demo.append(controls);const [prev,play,next]=controls.querySelectorAll('button');function render(){demo.querySelector('.conversation-label').textContent=scenes[current][0];demo.querySelector('.conversation-bubble').textContent=scenes[current][1];demo.querySelector('.conversation-note').textContent=scenes[current][2];controls.querySelector('.demo-caption').textContent=`Ejemplo ilustrativo · ${current+1} / 3`;}function stop(){clearInterval(timer);timer=null;play.textContent='Reproducir';play.setAttribute('aria-label','Reproducir demostración');}prev.onclick=()=>{stop();current=(current+2)%3;render();};next.onclick=()=>{stop();current=(current+1)%3;render();};play.onclick=()=>{if(timer){stop();return;}play.textContent='Pausar';play.setAttribute('aria-label','Pausar demostración');timer=setInterval(()=>{current=(current+1)%3;render();},4000);};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});render();
})();
