/* Logical 1000×720 room. Pointer movement is visual; operational edits use fgv_save_table. */
(() => {
  let state={groups:[],canCombine:false,suggested:null,objects:[],objectId:null,canDesign:false,roomId:null,rooms:[],canRooms:false,loaded:null,tables:[],items:[],revision:0,selected:null,editable:false,dirty:false,saving:false,failed:false,generation:0};
  const $=id=>document.getElementById(id), esc=value=>FGV.esc(value);
  const roomTables=()=>state.tables.filter(t=>(state.items.find(p=>p.table_id===t.id)?.room_id||null)===state.roomId);
  const roomName=()=>state.rooms.find(r=>r.id===state.roomId)?.name||'Sala principal';
  const roomOptions=(selected)=>state.rooms.map(r=>`<option value="${r.id||''}" ${r.id===selected?'selected':''}>${esc(r.name)}</option>`).join('');
  const position=(table,index)=>state.items.find(p=>p.table_id===table.id)||{table_id:table.id,x:60+(index%5)*185,y:Math.min(620,70+Math.floor(index/5)*145),shape:table.capacity<=2?'round':table.capacity<=4?'square':'rectangle'};
  function status(message,error=false){const el=$('floorStatus');if(el){el.textContent=message;el.className=error?'floor-status error':'floor-status';}$('floorRetry')?.toggleAttribute('hidden',!error);}
  function setItem(id,patch){let item=state.items.find(p=>p.table_id===id);if(!item){item=position(state.tables.find(t=>t.id===id),state.tables.findIndex(t=>t.id===id));state.items.push(item);}Object.assign(item,patch);state.dirty=true;state.failed=false;status('Cambios pendientes');}
  function paintPosition(button,item){button.style.left=(item.x/10)+'%';button.style.top=(item.y/7.2)+'%';button.dataset.shape=item.shape;}
  async function persist(){
    if(state.saving||!state.dirty||!state.editable)return;
    state.saving=true;state.failed=false;state.dirty=false;status('Guardando…');
    const snapshot=state.items.map(item=>({...item}));
    try{const result=await FGV.rpc(state.canDesign?'fgv_save_room_layout':'fgv_save_floor_plan',{p_revision:state.revision,p_items:snapshot,...(state.canDesign?{p_objects:state.objects.map(o=>({...o}))}:{})});state.revision=result.revision;status(state.dirty?'Guardando…':'Guardado');}
    catch(e){state.dirty=true;state.failed=true;status(e.message||'No se pudo guardar. Reintenta antes de salir.',true);}
    finally{state.saving=false;if(state.dirty&&!state.failed)persist();}
  }
  function select(id){state.objectId=null;state.selected=id;$('floorCanvas').querySelectorAll('[data-object]').forEach(b=>b.classList.remove('is-selected'));$('floorCanvas').querySelectorAll('[data-table]').forEach(b=>{b.classList.toggle('is-selected',b.dataset.table===id);b.setAttribute('aria-pressed',b.dataset.table===id?'true':'false');});editor();}
  function editor(){
    if(state.objectId){objectEditor();return;}
    const table=state.tables.find(t=>t.id===state.selected),root=$('floorEditor');
    if(!table){root.innerHTML='<div class="editor-empty"><span class="empty-symbol">⌘</span><h3>Tu sala, a tu manera.</h3><p>Selecciona una mesa para ver sus plazas y editarla.</p><small>En modo edición puedes arrastrar o usar las flechas del teclado.</small></div>';return;}
    const item=position(table,state.tables.indexOf(table)),group=state.groups.find(g=>g.table_ids.includes(table.id));
    root.innerHTML=`<div class="workspace-kicker">MESA SELECCIONADA</div><h2>${esc(table.name)}</h2><p class="fgv-muted">${table.capacity} plazas · ${table.active?'Activa':'Inactiva'}</p><form id="floorTableForm"><label>Nombre<input name="name" required maxlength="80" value="${esc(table.name)}"></label><label>Plazas<input name="capacity" type="number" required min="1" max="100" value="${table.capacity}"></label><label>Sala<select name="room">${roomOptions(item.room_id||null)}</select></label><label>Forma<select name="shape"><option value="round">Redonda</option><option value="square">Cuadrada</option><option value="rectangle">Rectangular</option></select></label><label class="check-label"><input name="active" type="checkbox" ${table.active?'checked':''}>Disponible para reservas</label><button type="submit" class="primary-action">Guardar mesa</button><p id="floorTableMessage" role="status" class="fgv-muted"></p></form><p class="fgv-muted">Cambiar las plazas o desactivar una mesa no puede perjudicar reservas aceptadas.</p>${state.canCombine?`<div class="combine-panel"><h3>Mesas combinadas</h3>${group?`<p>${group.table_ids.map(id=>esc(state.tables.find(t=>t.id===id)?.name)).join(' + ')} · ${group.capacity} plazas conjuntas</p><button type="button" id="floorUngroup" class="quiet-button">Descombinar</button>`:''}<label>Combinar con<select id="floorCombineTarget"><option value="">Elige otra mesa</option>${roomTables().filter(t=>t.active&&t.id!==table.id&&!group?.table_ids.includes(t.id)).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label><button type="button" id="floorCombine" class="quiet-button">Revisar combinación</button><p id="floorCombineMessage" role="status" class="fgv-muted"></p></div>`:''}`;
    if(state.canCombine){if(state.suggested&&$('floorCombineTarget'))$('floorCombineTarget').value=state.suggested;$('floorCombine').onclick=()=>{try{openCombine(table.id,$('floorCombineTarget').value);}catch(e){$('floorCombineMessage').textContent=e.message||'No se pudo abrir la combinación.';}};if(group)$('floorUngroup').onclick=async()=>{try{if(state.saving)throw Error('Espera a que termine el guardado.');await persist();if(state.dirty)return;const plan=await FGV.rpc('fgv_remove_table_group',{p_revision:state.revision,p_group_id:group.id});state.groups=plan.groups;state.revision=plan.revision;renderCanvas();editor();status('Descombinadas. Las reservas aceptadas conservan sus mesas.');}catch(e){$('floorCombineMessage').textContent=e.message;}};}
    const form=$('floorTableForm');form.elements.shape.value=item.shape;form.querySelectorAll('input,select,button').forEach(el=>el.disabled=!state.editable);
    form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button'),message=$('floorTableMessage');button.disabled=true;message.textContent='Guardando…';try{await FGV.rpc('fgv_save_table',{p_table_id:table.id,p_name:form.elements.name.value,p_capacity:Number(form.elements.capacity.value),p_active:form.elements.active.checked});table.name=form.elements.name.value.trim();table.capacity=Number(form.elements.capacity.value);table.active=form.elements.active.checked;setItem(table.id,{shape:form.elements.shape.value,room_id:form.elements.room.value||null});await persist();renderCanvas();message.textContent='Mesa guardada.';}catch(e){message.textContent=e.message||'No se pudo guardar.';}finally{button.disabled=!state.editable;}};
  }
  function renderCanvas(){
    const canvas=$('floorCanvas'),editing=$('floorEditMode').checked&&state.editable;
    const active=roomTables().filter(t=>t.active);canvas.dataset.room=roomName();canvas.setAttribute('aria-label','Plano de '+roomName());canvas.classList.toggle('is-editing',editing);
    canvas.innerHTML=active.map((table,index)=>{const p=position(table,index);return `<button type="button" class="floor-table ${table.id===state.selected?'is-selected':''}" data-table="${table.id}" data-combined="${state.groups.some(g=>g.table_ids.includes(table.id))}" data-shape="${p.shape}" aria-label="${esc(table.name)}, ${table.capacity} plazas" aria-pressed="${table.id===state.selected}" style="left:${p.x/10}%;top:${p.y/7.2}%"><span class="table-seats" aria-hidden="true"></span><strong>${esc(table.name)}</strong><small>${table.capacity} plazas</small></button>`;}).join('');
    if(!active.length&&!state.objects.some(o=>(o.room_id||null)===state.roomId))canvas.innerHTML='<div class="floor-empty"><h3>Imagina tu próximo servicio.</h3><p>Añade la primera mesa para empezar a dibujar tu sala.</p></div>';
    renderObjects(canvas,editing);
    $('floorCount').textContent=`${active.length} mesas · ${active.reduce((n,t)=>n+t.capacity,0)} plazas en mesas`;
    $('floorInactive').innerHTML=roomTables().some(t=>!t.active)?`<details><summary>Mesas inactivas (${roomTables().filter(t=>!t.active).length})</summary>${roomTables().filter(t=>!t.active).map(t=>`<button class="quiet-button" data-inactive="${t.id}">${esc(t.name)} · ${t.capacity} plazas</button>`).join('')}</details>`:'';
    $('floorInactive').querySelectorAll('[data-inactive]').forEach(b=>b.onclick=()=>select(b.dataset.inactive));
    canvas.querySelectorAll('[data-table]').forEach(button=>{
      const id=button.dataset.table;let drag=null;
      button.onclick=()=>select(id);
      button.onpointerdown=event=>{if(event.button!==0||!editing)return;const table=state.tables.find(t=>t.id===id),item=position(table,state.tables.filter(t=>t.active).findIndex(t=>t.id===id));select(id);drag={pointer:event.pointerId,startX:event.clientX,startY:event.clientY,x:item.x,y:item.y,lastX:item.x,lastY:item.y,moved:false};button.setPointerCapture(event.pointerId);button.classList.add('dragging');};
      button.onpointermove=event=>{if(!drag||drag.pointer!==event.pointerId)return;const rect=canvas.getBoundingClientRect(),dx=(event.clientX-drag.startX)/rect.width*1000,dy=(event.clientY-drag.startY)/rect.height*720;if(Math.abs(dx)+Math.abs(dy)>3)drag.moved=true;drag.lastX=Math.max(0,Math.min(870,Math.round((drag.x+dx)/5)*5));drag.lastY=Math.max(0,Math.min(620,Math.round((drag.y+dy)/5)*5));const near=nearTable(id,drag.lastX,drag.lastY);state.suggested=near?.id||null;canvas.querySelectorAll('[data-table]').forEach(b=>b.classList.toggle('snap-neighbor',b.dataset.table===state.suggested));if(near){drag.lastX=near.x;drag.lastY=near.y;}paintPosition(button,{...position(state.tables.find(t=>t.id===id),0),x:drag.lastX,y:drag.lastY});};
      const finish=event=>{if(!drag||event.pointerId!==drag.pointer)return;if(drag.moved){setItem(id,{x:drag.lastX,y:drag.lastY});persist();}drag=null;button.classList.remove('dragging');if(state.suggested)editor();};
      button.onpointerup=finish;button.onpointercancel=finish;
      button.onkeydown=event=>{if(!editing||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const item=position(state.tables.find(t=>t.id===id),active.findIndex(t=>t.id===id)),step=event.shiftKey?25:5;setItem(id,{x:Math.max(0,Math.min(870,item.x+(event.key==='ArrowRight'?step:event.key==='ArrowLeft'?-step:0))),y:Math.max(0,Math.min(620,item.y+(event.key==='ArrowDown'?step:event.key==='ArrowUp'?-step:0)))});paintPosition(button,state.items.find(p=>p.table_id===id));persist();};
    });
  }
  function nearTable(id,x,y){if(!state.canCombine)return null;const table=state.tables.find(t=>t.id===id),own=position(table,0),w=own.shape==='rectangle'?130:100,h=94;for(const other of roomTables().filter(t=>t.active&&t.id!==id)){if(state.groups.some(g=>g.table_ids.includes(id)&&g.table_ids.includes(other.id)))continue;const p=position(other,0),ow=p.shape==='rectangle'?130:100;if(Math.min(y+h,p.y+h)-Math.max(y,p.y)>35){if(Math.abs(x+w+12-p.x)<14)return{id:other.id,x:Math.max(0,p.x-w-12),y:p.y};if(Math.abs(x-p.x-ow-12)<14)return{id:other.id,x:Math.min(870,p.x+ow+12),y:p.y};}if(Math.min(x+w,p.x+ow)-Math.max(x,p.x)>35){if(Math.abs(y+h+12-p.y)<14)return{id:other.id,x:p.x,y:Math.max(0,p.y-h-12)};if(Math.abs(y-p.y-h-12)<14)return{id:other.id,x:p.x,y:Math.min(620,p.y+h+12)};}}return null;}
  function openCombine(first,second){if(!second){$('floorCombineMessage').textContent='Elige la otra mesa.';return;}const ids=new Set([first,second]);state.groups.filter(g=>g.table_ids.includes(first)||g.table_ids.includes(second)).forEach(g=>g.table_ids.forEach(id=>ids.add(id)));const members=[...ids],capacity=Math.min(100,members.reduce((n,id)=>n+state.tables.find(t=>t.id===id).capacity,0)),form=$('floorCombineForm');$('floorCombineNames').textContent=members.map(id=>state.tables.find(t=>t.id===id).name).join(' + ');form.elements.capacity.value=capacity;form.elements.capacity.max=capacity;$('floorCombineError').textContent='';$('floorCombineDialog').showModal();form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{if(state.saving)throw Error('Espera a que termine el guardado del plano.');await persist();if(state.dirty)throw Error('Guarda el plano antes de combinar.');const plan=await FGV.rpc('fgv_save_table_group',{p_revision:state.revision,p_table_ids:members,p_capacity:Number(form.elements.capacity.value)});state.groups=plan.groups;state.revision=plan.revision;state.suggested=null;$('floorCombineDialog').close();renderCanvas();editor();status('Combinación guardada');}catch(e){$('floorCombineError').textContent=e.message||'No se pudo combinar.';}finally{button.disabled=false;}};}
  function objectChanged(){state.dirty=true;state.failed=false;status('Cambios pendientes');persist();}
  function selectObject(id){state.selected=null;state.objectId=id;$('floorCanvas').querySelectorAll('[data-table]').forEach(b=>{b.classList.remove('is-selected');b.setAttribute('aria-pressed','false');});$('floorCanvas').querySelectorAll('[data-object]').forEach(b=>{b.classList.toggle('is-selected',b.dataset.object===id);b.setAttribute('aria-pressed',String(b.dataset.object===id));});objectEditor();}
  function addObject(kind){if(!state.canDesign)return;const object={id:crypto.randomUUID(),room_id:state.roomId,kind,label:kind==='bar'?'Barra':kind==='label'?'Entrada':'Muro',x:70,y:570,width:kind==='wall'?240:200,height:kind==='wall'?16:kind==='bar'?65:35};state.objects.push(object);$('floorEditMode').checked=true;renderCanvas();selectObject(object.id);objectChanged();}
  function objectEditor(){const object=state.objects.find(o=>o.id===state.objectId);if(!object){state.objectId=null;editor();return;}const root=$('floorEditor');root.innerHTML=`<div class="workspace-kicker">ELEMENTO DEL RESTAURANTE</div><h2>${esc(object.label||'Elemento')}</h2><form id="floorObjectForm"><label>Nombre del elemento<input name="label" maxlength="80" value="${esc(object.label)}"></label><div class="object-dimensions"><label>Ancho<input name="width" type="number" min="10" max="900" required value="${object.width}"></label><label>Alto<input name="height" type="number" min="10" max="620" required value="${object.height}"></label></div><p class="fgv-muted">Medidas relativas al plano. Ajusta la proporción de tu espacio.</p><button type="submit" class="primary-action">Guardar elemento</button><div class="fgv-toolbar"><button type="button" id="objectRotate" class="quiet-button">Girar 90°</button><button type="button" id="objectDelete" class="quiet-button">Eliminar elemento</button></div><p id="floorObjectMessage" role="status" class="fgv-muted"></p></form>`;const form=$('floorObjectForm');form.querySelectorAll('input,button').forEach(e=>e.disabled=!state.canDesign);form.onsubmit=event=>{event.preventDefault();object.label=form.elements.label.value.trim();object.width=Number(form.elements.width.value);object.height=Number(form.elements.height.value);object.x=Math.max(0,Math.min(object.x,1000-object.width));object.y=Math.max(0,Math.min(object.y,720-object.height));renderCanvas();objectChanged();$('floorObjectMessage').textContent='Cambios enviados al guardado del plano.';};$('objectRotate').onclick=()=>{if(object.width>620){$('floorObjectMessage').textContent='Reduce el ancho a 620 o menos para girarlo dentro del plano.';return;}[object.width,object.height]=[object.height,object.width];object.x=Math.min(object.x,1000-object.width);object.y=Math.min(object.y,720-object.height);renderCanvas();objectEditor();objectChanged();};$('objectDelete').onclick=()=>{state.objects=state.objects.filter(o=>o.id!==object.id);state.objectId=null;renderCanvas();editor();objectChanged();};}
  function renderObjects(canvas,editing){const objects=state.objects.filter(o=>(o.room_id||null)===state.roomId);canvas.insertAdjacentHTML('afterbegin',objects.map(o=>`<button type="button" class="floor-object ${o.id===state.objectId?'is-selected':''}" data-object="${o.id}" data-kind="${o.kind}" style="left:${o.x/10}%;top:${o.y/7.2}%;width:${o.width/10}%;height:${o.height/7.2}%" aria-label="${esc(o.label||o.kind)}, elemento del plano" aria-pressed="${o.id===state.objectId}">${o.kind==='wall'?'':esc(o.label)}</button>`).join(''));canvas.querySelectorAll('[data-object]').forEach(button=>{const o=state.objects.find(o=>o.id===button.dataset.object);let drag;button.onclick=()=>selectObject(o.id);button.onpointerdown=event=>{if(!editing||!state.canDesign||event.button!==0)return;selectObject(o.id);drag={id:event.pointerId,x:o.x,y:o.y,startX:event.clientX,startY:event.clientY,lastX:o.x,lastY:o.y};button.setPointerCapture(event.pointerId);button.classList.add('dragging');};button.onpointermove=event=>{if(!drag||event.pointerId!==drag.id)return;const rect=canvas.getBoundingClientRect();drag.lastX=Math.max(0,Math.min(1000-o.width,Math.round((drag.x+(event.clientX-drag.startX)/rect.width*1000)/5)*5));drag.lastY=Math.max(0,Math.min(720-o.height,Math.round((drag.y+(event.clientY-drag.startY)/rect.height*720)/5)*5));button.style.left=drag.lastX/10+'%';button.style.top=drag.lastY/7.2+'%';};const finish=event=>{if(!drag||event.pointerId!==drag.id)return;const changed=o.x!==drag.lastX||o.y!==drag.lastY;o.x=drag.lastX;o.y=drag.lastY;drag=null;button.classList.remove('dragging');if(changed)objectChanged();};button.onpointerup=finish;button.onpointercancel=finish;button.onkeydown=event=>{if(!editing||!state.canDesign||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const step=event.shiftKey?25:5;o.x=Math.max(0,Math.min(1000-o.width,o.x+(event.key==='ArrowRight'?step:event.key==='ArrowLeft'?-step:0)));o.y=Math.max(0,Math.min(720-o.height,o.y+(event.key==='ArrowDown'?step:event.key==='ArrowUp'?-step:0)));button.style.left=o.x/10+'%';button.style.top=o.y/7.2+'%';objectChanged();};});}
  window.floorHasUnsavedChanges=()=>state.dirty||state.saving;
  window.addEventListener('beforeunload',event=>{if(window.floorHasUnsavedChanges()){event.preventDefault();event.returnValue='';}});
  window.loadFloorPlan=async()=>{
    const root=$('floorContent');if(state.loaded===establishmentId&&(state.dirty||state.saving))return;
    const generation=++state.generation;root.innerHTML='<div class="skeleton" role="status">Preparando tu sala…</div>';
    try{
      const [tables,plan,features]=await Promise.all([supabaseClient.from('restaurant_tables').select('*').eq('establishment_id',establishmentId).order('name'),FGV.rpc('fgv_get_floor_plan'),FGV.rpc('fgv_get_features')]);if(tables.error)throw tables.error;if(generation!==state.generation)return;
      state={...state,loaded:establishmentId,tables:tables.data,groups:plan.groups||[],canCombine:features.table_combinations===true,objects:plan.objects||[],objectId:null,canDesign:features.floor_designer===true,items:plan.items,rooms:plan.rooms||[{id:null,name:'Sala principal'}],canRooms:features.multiple_rooms===true,revision:plan.revision,editable:features.visual_floor_plan===true,dirty:false,failed:false,selected:null};
      if(!state.rooms.some(r=>r.id===state.roomId))state.roomId=null;
      // Deterministic initial placement is not persisted until the owner moves or edits a table.
      state.tables.filter(t=>t.active).forEach((table,index)=>{if(!state.items.some(p=>p.table_id===table.id))state.items.push(position(table,index));});
      root.innerHTML=`<div class="floor-toolbar"><div><label class="room-tab" for="floorRoom">Sala<select id="floorRoom" aria-label="Elegir sala">${roomOptions(state.roomId)}</select></label><button id="floorAddRoom" class="quiet-button room-add" ${state.canRooms?'':'disabled'}>+ Nueva sala</button><p id="floorCount" class="fgv-muted"></p></div><div class="floor-actions"><span id="floorStatus" class="floor-status" role="status">${plan.revision?'Guardado':'Listo para organizar'}</span><button id="floorRetry" class="quiet-button" hidden>Reintentar</button><button id="floorReload" class="quiet-button">Recargar</button><label class="edit-toggle"><input type="checkbox" id="floorEditMode" ${state.editable?'':'disabled'}>Editar plano</label><button id="floorAdd" class="primary-action" ${state.editable?'':'disabled'}>+ Añadir mesa</button></div></div>
      ${state.canDesign?'<div class="designer-tools" aria-label="Elementos del restaurante"><span>Diseña tu espacio</span><button type="button" id="floorToolTable">+ Mesa</button><button type="button" data-add-object="wall">+ Muro</button><button type="button" data-add-object="bar">+ Barra</button><button type="button" data-add-object="label">+ Texto</button><small>Selecciona un elemento para ajustar su tamaño.</small></div>':''}
      ${state.editable?'':'<p class="fgv-message">Puedes consultar la sala. La edición no está habilitada para este restaurante.</p>'}
      <div class="floor-workspace"><div class="floor-surface"><div class="floor-scroll"><div id="floorCanvas" class="floor-canvas" data-room="${esc(roomName())}" role="group" aria-label="Plano de Sala principal"></div></div><div class="floor-footnote"><span>PLANO DE DISTRIBUCIÓN</span><span>Las posiciones no representan disponibilidad.</span></div><div id="floorInactive"></div></div><aside id="floorEditor" class="surface floor-editor" aria-label="Editar mesa"></aside></div>
      <dialog id="floorCombineDialog" class="app-dialog"><form id="floorCombineForm"><div class="workspace-kicker">CONFIRMA LA COMBINACIÓN</div><h2>Reservar mesas juntas</h2><p id="floorCombineNames"></p><label>Plazas al juntarlas<input name="capacity" type="number" min="1" max="100" required></label><p class="fgv-muted">El motor podrá reservarlas juntas y bloqueará todas durante esa reserva. Siguen disponibles por separado cuando estén libres. Se respetan el aforo y el máximo de personas configurados.</p><div class="fgv-toolbar"><button type="submit" class="primary-action">Confirmar combinación</button><button type="button" id="floorCombineClose" class="quiet-button">Cancelar</button></div><p id="floorCombineError" role="status"></p></form></dialog><dialog id="floorRoomDialog" class="app-dialog"><form id="floorRoomForm"><div class="workspace-kicker">ORGANIZA TU RESTAURANTE</div><h2>Nueva sala</h2><p class="fgv-muted">Cada sala tiene su propio plano. El aforo del restaurante se comparte entre todas.</p><label>Nombre de la sala<input name="name" required maxlength="80" placeholder="Terraza, comedor, planta superior…"></label><div class="fgv-toolbar"><button type="submit" class="primary-action">Crear sala</button><button type="button" id="floorRoomClose" class="quiet-button">Cancelar</button></div><p id="floorRoomMessage" role="status"></p></form></dialog><dialog id="floorAddDialog" class="app-dialog"><form id="floorAddForm"><div class="workspace-kicker">AMPLÍA TU SALA</div><h2>Nueva mesa</h2><p class="fgv-muted">Indica las plazas reales para calcular la disponibilidad.</p><label>Nombre<input name="name" required maxlength="80" placeholder="Mesa 16"></label><label>Plazas<input name="capacity" type="number" min="1" max="100" value="4" required></label><div class="fgv-toolbar"><button type="submit" class="primary-action">Crear mesa</button><button type="button" id="floorAddClose" class="quiet-button">Cancelar</button></div><p id="floorAddMessage" role="status"></p></form></dialog>`;
      $('floorCombineClose').onclick=()=>$('floorCombineDialog').close();
      $('floorEditMode').onchange=renderCanvas;
      $('floorRoom').onchange=async event=>{const next=event.target.value||null;if(state.saving){event.target.value=state.roomId||'';status('Espera a que termine el guardado.');return;}await persist();if(state.dirty){event.target.value=state.roomId||'';return;}state.roomId=next;state.selected=null;state.objectId=null;renderCanvas();editor();};
      $('floorAddRoom').onclick=()=>{$('floorRoomMessage').textContent='';$('floorRoomDialog').showModal();$('floorRoomForm').elements.name.focus();};$('floorRoomClose').onclick=()=>$('floorRoomDialog').close();
      $('floorRoomForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type=submit]');button.disabled=true;try{if(state.saving)throw Error('Espera a que termine el guardado del plano.');await persist();if(state.dirty)throw Error('Guarda el plano antes de añadir una sala.');const name=form.elements.name.value.trim(),plan=await FGV.rpc('fgv_save_room',{p_room_id:null,p_name:name,p_revision:state.revision});state.rooms=plan.rooms;state.revision=plan.revision;state.roomId=state.rooms.find(r=>r.name===name).id;state.selected=null;state.objectId=null;$('floorRoom').innerHTML=roomOptions(state.roomId);$('floorRoomDialog').close();form.reset();renderCanvas();editor();status('Sala creada');}catch(e){$('floorRoomMessage').textContent=e.message||'No se pudo crear la sala.';}finally{button.disabled=false;}};$('floorRetry').onclick=persist;$('floorReload').onclick=()=>{if(state.saving)return;if(state.dirty&&!confirm('Hay posiciones sin guardar. ¿Descartar esos cambios y cargar el plano guardado?'))return;state.dirty=false;window.loadFloorPlan();};
      $('floorAdd').onclick=()=>{$('floorAddDialog').showModal();$('floorAddForm').elements.name.focus();};if($('floorToolTable'))$('floorToolTable').onclick=()=>$('floorAdd').click();$('floorAddClose').onclick=()=>$('floorAddDialog').close();
      $('floorAddForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type=submit]');button.disabled=true;try{const name=form.elements.name.value.trim(),capacity=Number(form.elements.capacity.value),id=await FGV.rpc('fgv_save_table',{p_table_id:null,p_name:name,p_capacity:capacity,p_active:true});state.tables.push({id,name,capacity,active:true});const i=roomTables().filter(t=>t.active).length;setItem(id,{room_id:state.roomId,x:Math.min(870,60+(i%5)*185),y:Math.min(620,70+Math.floor(i/5)*145),shape:capacity<=2?'round':capacity<=4?'square':'rectangle'});await persist();$('floorAddDialog').close();form.reset();renderCanvas();select(id);}catch(e){$('floorAddMessage').textContent=e.message||'No se pudo crear la mesa.';}finally{button.disabled=false;}};
      root.querySelectorAll('[data-add-object]').forEach(b=>b.onclick=()=>addObject(b.dataset.addObject));
      renderCanvas();editor();
    }catch(e){root.innerHTML=`<div class="fgv-message fgv-error" role="alert">${esc(e.message||'No se pudo cargar la sala.')}<p>Vuelve a abrir Sala para reintentar.</p></div>`;}
  };
})();
