CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.role',true),'') $$;
GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;
CREATE TABLE public.establishments (id uuid DEFAULT gen_random_uuid() PRIMARY KEY,name text NOT NULL,business_type text NOT NULL,phone text,email text,address text,timezone text NOT NULL DEFAULT 'Europe/Madrid',language text NOT NULL DEFAULT 'es',status text NOT NULL DEFAULT 'draft',active bool NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),city text);
CREATE TABLE public.profiles(id uuid PRIMARY KEY,full_name text,role text NOT NULL DEFAULT 'client',created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE public.establishment_users(id uuid DEFAULT gen_random_uuid() PRIMARY KEY,establishment_id uuid NOT NULL REFERENCES establishments(id),user_id uuid NOT NULL REFERENCES profiles(id),role text NOT NULL DEFAULT 'client',created_at timestamptz DEFAULT now(),UNIQUE(establishment_id,user_id));
CREATE TABLE public.establishment_config(id uuid DEFAULT gen_random_uuid() PRIMARY KEY,establishment_id uuid NOT NULL UNIQUE REFERENCES establishments(id),config jsonb NOT NULL DEFAULT '{}',created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE public.business_rules(id uuid DEFAULT gen_random_uuid() PRIMARY KEY,establishment_id uuid NOT NULL REFERENCES establishments(id),name text NOT NULL,rule_type text,rule jsonb NOT NULL DEFAULT '{}',active bool NOT NULL DEFAULT true,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE public.customers(id uuid DEFAULT gen_random_uuid() PRIMARY KEY,establishment_id uuid NOT NULL REFERENCES establishments(id),name text,phone text,email text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE public.reservations(id uuid DEFAULT gen_random_uuid() PRIMARY KEY,establishment_id uuid NOT NULL REFERENCES establishments(id),customer_id uuid REFERENCES customers(id),service_id uuid,external_id text,reservation_type text,start_at timestamptz,end_at timestamptz,party_size int,status text NOT NULL DEFAULT 'pending',metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE FUNCTION public.get_my_role() RETURNS text LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ SELECT role FROM public.profiles WHERE id=auth.uid() $$;
CREATE FUNCTION public.get_reservations(p_establishment_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER AS $$ SELECT coalesce(jsonb_agg(to_jsonb(r)),'[]'::jsonb) FROM public.reservations r WHERE establishment_id=p_establishment_id $$;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE establishment_users ENABLE ROW LEVEL SECURITY; ALTER TABLE establishment_config ENABLE ROW LEVEL SECURITY; ALTER TABLE business_rules ENABLE ROW LEVEL SECURITY; ALTER TABLE customers ENABLE ROW LEVEL SECURITY; ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_can_read_own_profile ON profiles FOR SELECT TO authenticated USING(id=auth.uid());
CREATE POLICY users_can_read_own_establishment_membership ON establishment_users FOR SELECT TO authenticated USING(user_id=auth.uid());
CREATE POLICY users_can_insert_own_establishment_membership ON establishment_users FOR INSERT TO authenticated WITH CHECK(user_id=auth.uid());
CREATE POLICY "Allow public read establishments" ON establishments FOR SELECT USING(true);
CREATE POLICY allow_onboarding_insert_establishments ON establishments FOR INSERT TO anon,authenticated WITH CHECK(true);
CREATE POLICY "Allow public insert on establishment_config" ON establishment_config FOR INSERT WITH CHECK(true);
CREATE POLICY "Allow public read establishment config" ON establishment_config FOR SELECT USING(true);
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon,authenticated,service_role;
