import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs'; import assert from 'node:assert/strict'; import {randomUUID as uuid} from 'node:crypto';
const db=new PGlite(),here=new URL('./',import.meta.url);let count=0;
await db.exec(fs.readFileSync(new URL('baseline.sql',here),'utf8'));
for(const f of fs.readdirSync(new URL('../supabase/migrations/',here)).filter(f=>f.endsWith('.sql')).sort())await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+f,here),'utf8'));
const rpc=async(n,a)=>(await db.query(`select public.${n}(${a.map((_,i)=>'$'+(i+1)).join(',')}) as v`,a)).rows[0].v;
async function test(n,f){await f();count++;console.log('PASS',n);}
const owner=uuid(),other=uuid();await db.query("insert into profiles(id,role) values($1,'owner'),($2,'owner')",[owner,other]);
async function login(id,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role',$2,false)",[id||'',role]);await db.exec('set role '+role);}
const schedules=Object.fromEntries(['monday','tuesday','wednesday','thursday','friday','saturday','sunday'].map(d=>[d,{closed:false,services:[{open:'12:00',close:'23:00'}]}]));
const setup={total_capacity:6,max_people:6,duration_minutes:60,min_notice_minutes:0,max_advance_days:730,schedules};
const payload={establishment:{name:'Test',business_type:'restaurant',timezone:'Europe/Madrid'},config:{reservation_type:'manual'},business_rules:{schedules}};
await login(owner);const key=uuid();const e=await rpc('fgv_complete_onboarding',[payload,key]),id=e.id;
await test('Onboarding is atomic and retry-safe',async()=>{assert.equal((await rpc('fgv_complete_onboarding',[payload,key])).id,id);assert.equal((await db.query('select count(*)::int n from establishment_users')).rows[0].n,1);});
await test('Setup required',()=>assert.rejects(rpc('fgv_check_availability',[id,'2026-09-09T13:00',2,null]),/Configura primero/));
await rpc('fgv_save_settings',[id,setup]);const t2=await rpc('fgv_save_table',[id,null,'Mesa 2',2,true]);await rpc('fgv_save_table',[id,null,'Mesa 4',4,true]);
const date=(await db.query("select ((now() at time zone 'Europe/Madrid')::date+2)::text d")).rows[0].d,at=t=>date+'T'+t;
const create=(t,n,key=uuid())=>rpc('fgv_save_reservation',[id,at(t),n,'Prueba','+34600000000','',key,null,null]);
let a,b;
await test('Smallest table and one-hour duration',async()=>{a=await create('13:00',2);assert.equal(a.table_id,t2);assert.equal(Date.parse(a.end_at)-Date.parse(a.start_at),3600000);});
await test('Duplicate retry creates one reservation',async()=>{const k=uuid();b=await create('13:00',4,k);assert.equal((await create('13:00',4,k)).id,b.id);await assert.rejects(create('13:00',3,k),/otros datos/);});
await test('No overbooking',()=>assert.rejects(create('13:30',2),/aforo|mesa/));
await test('Adjacent intervals can reuse a table',async()=>assert.equal((await create('14:00',2)).table_id,t2));
await test('Whole booking must fit opening hours',async()=>{assert.equal((await rpc('fgv_check_availability',[id,at('22:00'),2,null])).available,true);assert.equal((await rpc('fgv_check_availability',[id,at('22:30'),2,null])).available,false);});
await test('Reject past dates and invalid party size',async()=>{assert.equal((await rpc('fgv_check_availability',[id,'2020-01-01T13:00',2,null])).available,false);await assert.rejects(create('15:00',0),/válidos/);await assert.rejects(create('15:00',7),/válidos/);});
await test('Edit excludes itself, revision prevents stale edits',async()=>{a=await rpc('fgv_save_reservation',[id,at('15:00'),2,'Editada','+34600000000','Nota',uuid(),a.id,1]);assert.equal(a.revision,2);await assert.rejects(rpc('fgv_save_reservation',[id,at('16:00'),2,'Editada','+34600000000','',uuid(),a.id,1]),/ha cambiado/);});
await test('Cancellation frees space, retry safe',async()=>{await rpc('fgv_cancel_reservation',[id,b.id,1]);await rpc('fgv_cancel_reservation',[id,b.id,1]);assert.equal((await rpc('fgv_check_availability',[id,at('13:00'),4,null])).available,true);});
await test('Prevent deactivating booked table',()=>assert.rejects(rpc('fgv_save_table',[id,t2,'Mesa 2',2,false]),/reservas futuras/));
await test('Compatible rule changes preserve accepted reservations',async()=>{await rpc('fgv_save_settings',[id,{...setup,duration_minutes:90,max_people:1}]); const saved=(await rpc('fgv_list_reservations',[id,date])).find(r=>r.id===a.id); assert.equal(saved.end_at,a.end_at); await rpc('fgv_save_settings',[id,setup]);});
await test('Incompatible capacity and opening changes rejected atomically',async()=>{await assert.rejects(rpc('fgv_save_settings',[id,{...setup,total_capacity:1}]),/aforo debe/); await assert.rejects(rpc('fgv_save_settings',[id,{...setup,schedules:Object.fromEntries(Object.keys(schedules).map(d=>[d,{closed:true}]))}]),/fuera de apertura/); assert.equal((await db.query('select total_capacity from reservation_settings where establishment_id=$1',[id])).rows[0].total_capacity,6);});
const profile={name:'Restaurante editado',business_type:'restaurant',phone:'+34 600 000 000',email:'owner@example.com',address:'Calle 1',city:'Madrid',timezone:'Europe/Madrid',language:'es',reservation_type:'manual',reservation_system:''};
await test('Owner edits profile without privileged field injection',async()=>{const updated=await rpc('fgv_update_restaurant',[id,{...profile,active:false,created_by:other,config:{secret:'injected'}},1]); assert.equal(updated.name,profile.name); assert.equal(updated.active,true); assert.equal(updated.created_by,owner); assert.equal(updated.settings_revision,2); assert.equal(updated.city,profile.city); assert.equal((await db.query('select config from establishment_config where establishment_id=$1',[id])).rows[0].config.city,profile.city);});
await test('Profile validation, concurrent edits and booked mode switch',async()=>{await assert.rejects(rpc('fgv_update_restaurant',[id,profile,1]),/Otra persona/); await assert.rejects(rpc('fgv_update_restaurant',[id,{...profile,email:'invalid'},2]),/correo/); await assert.rejects(rpc('fgv_update_restaurant',[id,{...profile,reservation_type:'digital',reservation_system:'thefork'},2]),/traslado/);});
await test('Day list includes table names',async()=>assert.equal((await rpc('fgv_list_reservations',[id,date])).find(r=>r.id===a.id).table_name,'Mesa 2'));
await test('Direct writes and self-claim denied',async()=>{await assert.rejects(db.query('insert into reservations(establishment_id) values($1)',[id]),/permission denied/);await assert.rejects(db.query('insert into establishment_users(establishment_id,user_id) values($1,$2)',[id,owner]),/permission denied/);await assert.rejects(db.query("update profiles set role='superadmin'"),/permission denied/);});
await login(other);const e2=await rpc('fgv_complete_onboarding',[payload,uuid()]);
await test('Tenant isolation: reads, availability, cancellation',async()=>{assert.equal((await db.query('select * from reservations')).rows.length,0);assert.equal((await db.query('select * from restaurant_tables')).rows.length,0);await assert.rejects(rpc('fgv_check_availability',[id,at('13:00'),2,null]),/acceso/);await assert.rejects(rpc('fgv_cancel_reservation',[id,a.id,2]),/acceso/);assert.equal((await db.query('select * from establishments')).rows.length,1);});
await test('Other tenants cannot edit restaurant or settings',async()=>{await assert.rejects(rpc('fgv_update_restaurant',[id,profile,2]),/acceso/);await assert.rejects(rpc('fgv_save_settings',[id,setup]),/acceso/);});
await test('Legacy definer access blocked',()=>assert.rejects(rpc('get_reservations',[id]),/permission denied/));
await login(null,'anon');await test('Anonymous access blocked',async()=>{await assert.rejects(db.query('select * from establishments'),/permission denied/);await assert.rejects(rpc('fgv_check_availability',[id,at('13:00'),2,null]),/permission denied/);});
await login(other);const night=Object.fromEntries(Object.keys(schedules).map(d=>[d,{closed:false,services:[{open:'20:00',close:'02:00'}]}]));
await rpc('fgv_save_settings',[e2.id,{...setup,schedules:night}]);await rpc('fgv_save_table',[e2.id,null,'Noche',6,true]);
await test('Overnight opening',async()=>{assert.equal((await rpc('fgv_check_availability',[e2.id,at('00:30'),2,null])).available,true);assert.equal((await rpc('fgv_check_availability',[e2.id,at('01:30'),2,null])).available,false);});
await test('DST missing and repeated hours',async()=>{await assert.rejects(rpc('fgv_check_availability',[e2.id,'2027-03-28T02:30',2,null]),/no existe/);await assert.rejects(rpc('fgv_check_availability',[e2.id,'2026-10-25T02:30',2,null]),/se repite/);});
await test('Invalid schedule rejected',()=>assert.rejects(rpc('fgv_save_settings',[e2.id,{...setup,schedules:{...schedules,monday:{closed:false,services:[{open:'25:00',close:'26:00'}]}}}]),/Hora inválida/));
await test('Min and max notice',async()=>{await rpc('fgv_save_settings',[e2.id,{...setup,max_advance_days:0}]);assert.equal((await rpc('fgv_check_availability',[e2.id,at('13:00'),2,null])).available,false);await rpc('fgv_save_settings',[e2.id,{...setup,min_notice_minutes:10080}]);assert.equal((await rpc('fgv_check_availability',[e2.id,at('13:00'),2,null])).available,false);});
await test('External provider not falsely available',async()=>{const ext=await rpc('fgv_complete_onboarding',[{...payload,config:{reservation_type:'digital',reservation_system:'thefork'}},uuid()]);await assert.rejects(rpc('fgv_check_availability',[ext.id,at('13:00'),2,null]),/no utiliza/);});
await login(owner);
const layout=[{table_id:t2,x:100,y:200,shape:'round'}];
await test('Floor plan persists without changing bookings',async()=>{const saved=await rpc('fgv_save_floor_plan',[id,0,layout]);assert.equal(saved.revision,1);assert.deepEqual(saved.items,layout);assert.equal((await rpc('fgv_list_reservations',[id,date])).find(r=>r.id===a.id).end_at,a.end_at);});
await test('Floor rejects stale writes, duplicates and invalid positions',async()=>{await assert.rejects(rpc('fgv_save_floor_plan',[id,0,layout]),/otro dispositivo/);await assert.rejects(rpc('fgv_save_floor_plan',[id,1,[...layout,...layout]]),/una sola vez/);await assert.rejects(rpc('fgv_save_floor_plan',[id,1,[{...layout[0],x:901}]]),/check constraint/);assert.equal((await rpc('fgv_get_floor_plan',[id])).revision,1);});
await test('Floor ownership enforced for reads and individual items',async()=>{await assert.rejects(rpc('fgv_save_floor_plan',[e2.id,0,layout]),/acceso/);await assert.rejects(rpc('fgv_get_floor_plan',[e2.id]),/acceso/);await login(other);await assert.rejects(rpc('fgv_save_floor_plan',[e2.id,0,layout]),/no pertenece/);await login(owner);});
await test('Features cannot be self granted and are enforced by server',async()=>{await assert.rejects(db.query("update establishment_subscriptions set plan_key='pilot'"),/permission denied/);await login(null,'service_role');await db.query("update establishment_subscriptions set status='paused' where establishment_id=$1",[id]);await login(owner);await assert.rejects(rpc('fgv_save_floor_plan',[id,1,layout]),/no está habilitada/);assert.equal((await rpc('fgv_get_floor_plan',[id])).revision,1);});
await test('Complete onboarding configures engine without invented tables',async()=>{const complete=await rpc('fgv_complete_onboarding',[{...payload,business_rules:{total_capacity:20,max_people:6,stay_duration:'90',booking_advance:'7_days',schedules}},uuid()]);assert.equal((await db.query('select duration_minutes from reservation_settings where establishment_id=$1',[complete.id])).rows[0].duration_minutes,90);assert.equal((await rpc('fgv_get_features',[complete.id])).visual_floor_plan,true);assert.equal((await rpc('fgv_check_availability',[complete.id,at('13:00'),2,null])).available,false);});

const designEst=await rpc('fgv_complete_onboarding',[payload,uuid()]),designId=designEst.id;
await rpc('fgv_save_settings',[designId,setup]);const designTable=await rpc('fgv_save_table',[designId,null,'Interior 1',4,true]);let designPlan,terrace;
await test('Multiple rooms retain the principal room and reject duplicate names',async()=>{designPlan=await rpc('fgv_save_room',[designId,null,'Terraza',0]);terrace=designPlan.rooms.find(r=>r.name==='Terraza').id;assert.equal(designPlan.rooms.length,2);assert.equal(designPlan.rooms[0].name,'Sala principal');await assert.rejects(rpc('fgv_save_room',[designId,null,'terraza',1]),/existe/);await assert.rejects(rpc('fgv_save_room',[designId,null,'Sala principal',1]),/existe/);});
await test('Room layout persists and concurrent room edits are rejected',async()=>{designPlan=await rpc('fgv_save_floor_plan',[designId,1,[{table_id:designTable,room_id:terrace,x:50,y:80,shape:'square'}]]);assert.equal(designPlan.items[0].room_id,terrace);await assert.rejects(rpc('fgv_save_room',[designId,terrace,'Exterior',1]),/otro dispositivo/);designPlan=await rpc('fgv_save_room',[designId,terrace,'Exterior',2]);assert.equal(designPlan.rooms[1].name,'Exterior');});
await test('Rooms and table placement cannot cross tenants',async()=>{await assert.rejects(rpc('fgv_save_floor_plan',[designId,3,[{table_id:designTable,room_id:uuid(),x:50,y:80,shape:'square'}]]),/no pertenece/);await login(other);await assert.rejects(rpc('fgv_save_room',[designId,null,'Ajena',3]),/acceso/);assert.equal((await db.query('select count(*)::int n from restaurant_rooms where establishment_id=$1',[designId])).rows[0].n,0);await login(owner);});
const wall={id:uuid(),room_id:terrace,kind:'wall',label:'Separación',x:50,y:300,width:240,height:16};
await test('Walls and bar layouts save atomically and preserve table inventory',async()=>{designPlan=await rpc('fgv_save_room_layout',[designId,3,designPlan.items,[wall]]);assert.equal(designPlan.objects[0].kind,'wall');assert.equal((await db.query('select capacity from restaurant_tables where id=$1',[designTable])).rows[0].capacity,4);await assert.rejects(rpc('fgv_save_room_layout',[designId,4,[{...designPlan.items[0],x:70}],[{...wall,x:990}]]),/check constraint/);assert.equal((await rpc('fgv_get_floor_plan',[designId])).items[0].x,50);assert.equal((await rpc('fgv_get_floor_plan',[designId])).revision,4);});
await test('Objects reject duplicates, invalid rooms and cross-tenant reads',async()=>{await assert.rejects(rpc('fgv_save_room_layout',[designId,4,designPlan.items,[wall,wall]]),/una sola vez/);await assert.rejects(rpc('fgv_save_room_layout',[designId,4,designPlan.items,[{...wall,room_id:uuid()}]]),/no pertenece/);await login(other);assert.equal((await db.query('select count(*)::int n from floor_objects where id=$1',[wall.id])).rows[0].n,0);await assert.rejects(rpc('fgv_save_room_layout',[designId,4,[],[]]),/acceso/);await login(owner);});
await test('Object removal cannot change bookings or remove tables',async()=>{const before=(await db.query('select count(*)::int n from restaurant_tables where establishment_id=$1',[designId])).rows[0].n;designPlan=await rpc('fgv_save_room_layout',[designId,4,designPlan.items,[]]);assert.equal(designPlan.objects.length,0);assert.equal((await db.query('select count(*)::int n from restaurant_tables where establishment_id=$1',[designId])).rows[0].n,before);});


const designSecond=await rpc('fgv_save_table',[designId,null,'Exterior 2',2,true]);
designPlan=await rpc('fgv_save_floor_plan',[designId,5,[...designPlan.items,{table_id:designSecond,room_id:terrace,x:150,y:80,shape:'round'}]]);
let jointBooking,jointKey=uuid();
const createJoint=(time,people,key=uuid())=>rpc('fgv_save_reservation',[designId,at(time),people,'Grupo','+34600000009','',key,null,null]);
await test('Explicit table combination enables a larger group without adding seats',async()=>{assert.equal((await rpc('fgv_check_availability',[designId,at('16:00'),5,null])).available,false);designPlan=await rpc('fgv_save_table_group',[designId,6,[designTable,designSecond],5]);const slot=await rpc('fgv_check_availability',[designId,at('16:00'),5,null]);assert.equal(slot.available,true);assert.equal(slot.table_ids.length,2);assert.equal((await db.query('select sum(capacity)::int n from restaurant_tables where establishment_id=$1',[designId])).rows[0].n,6);});
await test('Combined bookings reserve every table and retries preserve allocation',async()=>{jointBooking=await createJoint('16:00',5,jointKey);assert.deepEqual(new Set(jointBooking.allocated_table_ids),new Set([designTable,designSecond]));assert.equal((await createJoint('16:00',5,jointKey)).id,jointBooking.id);assert.equal((await rpc('fgv_check_availability',[designId,at('16:30'),1,null])).available,false);const listed=(await rpc('fgv_list_reservations',[designId,date])).find(r=>r.id===jointBooking.id);assert.match(listed.table_name,/Interior 1/);assert.match(listed.table_name,/Exterior 2/);});
await test('Combined bookings allow adjacent slots and reject harmful table edits',async()=>{assert.equal((await rpc('fgv_check_availability',[designId,at('17:00'),5,null])).available,true);await assert.rejects(rpc('fgv_save_table',[designId,designSecond,'Exterior 2',2,false]),/reservas futuras/);await assert.rejects(rpc('fgv_save_table',[designId,designTable,'Interior 1',2,true]),/reservas futuras/);await rpc('fgv_save_table',[designId,designTable,'Interior 1',4,true]);});
await test('Combinations cannot invent seats or span rooms',async()=>{await assert.rejects(rpc('fgv_save_table_group',[designId,7,[designTable,designSecond],7]),/plazas reales/);await assert.rejects(rpc('fgv_save_floor_plan',[designId,7,designPlan.items.map(i=>i.table_id===designTable?{...i,room_id:null}:i)]),/Descombina/);await assert.rejects(rpc('fgv_save_table_group',[designId,7,[designTable,designTable],4]),/diferentes/);await login(other);await assert.rejects(rpc('fgv_save_table_group',[designId,7,[designTable,designSecond],5]),/acceso/);assert.equal((await db.query('select count(*)::int n from table_groups where establishment_id=$1',[designId])).rows[0].n,0);await login(owner);});
await test('Removing a combination preserves accepted allocations until cancellation',async()=>{designPlan=await rpc('fgv_remove_table_group',[designId,7,designPlan.groups[0].id]);assert.equal(designPlan.groups.length,0);assert.equal((await rpc('fgv_check_availability',[designId,at('16:30'),1,null])).available,false);await rpc('fgv_cancel_reservation',[designId,jointBooking.id,1]);assert.equal((await rpc('fgv_check_availability',[designId,at('16:30'),2,null])).available,true);assert.equal((await rpc('fgv_check_availability',[designId,at('16:30'),5,null])).available,false);});


await test('Channel setup stores a number without claiming activation',async()=>{const result=await rpc('fgv_request_channel_setup',[designId,'whatsapp','+34 600 000 010']);assert.equal(result.status,'pending_authorization');assert.equal(result.phone,'+34600000010');const setup=await rpc('fgv_get_commercial_setup',[designId]);assert.equal(setup.catalog.length,3);assert.equal(setup.channels.whatsapp.status,'pending_authorization');await assert.rejects(rpc('fgv_request_channel_setup',[designId,'whatsapp','incorrecto']),/prefijo/);});
await test('Channel setup is tenant isolated and subscription gates are enforced',async()=>{await login(other);await assert.rejects(rpc('fgv_request_channel_setup',[designId,'whatsapp','+34600000010']),/acceso/);await assert.rejects(rpc('fgv_get_commercial_setup',[designId]),/acceso/);await login(null,'service_role');await db.query("update establishment_subscriptions set plan_key='starter' where establishment_id=$1",[designId]);await login(owner);await assert.rejects(rpc('fgv_request_channel_setup',[designId,'voice','+34600000010']),/incluido/);await assert.rejects(rpc('fgv_save_room',[designId,null,'VIP',designPlan.revision]),/habilitada/);});


await test('Restaurant owners cannot read or write global administration',async()=>{await login(owner);await assert.rejects(rpc('fgv_admin_overview',[]),/administrador/);await assert.rejects(rpc('fgv_admin_save_account',[id,0,{stage:'contracted'}]),/administrador/);await assert.rejects(rpc('fgv_admin_create_restaurant',[{name:'Unauthorized'},uuid()]),/administrador/);await assert.rejects(db.query('select * from admin_accounts'),/permission denied/);});
const admin=uuid();await login(null,'service_role');await db.query("insert into profiles(id,role) values($1,'superadmin')",[admin]);await login(admin);
await test('Superadmin directory includes all restaurants and private commercial records',async()=>{const overview=await rpc('fgv_admin_overview',[]);assert(overview.restaurants.some(r=>r.id===id));assert(overview.restaurants.some(r=>r.id===e2.id));assert.equal(overview.restaurants.find(r=>r.id===id).stage,'trial');const saved=await rpc('fgv_admin_save_account',[id,0,{stage:'contracted',contact_name:'Responsable',contact_email:'test@example.com',notes:'Privado',next_follow_up:'2026-10-01'}]);assert.equal(saved.revision,1);const updated=await rpc('fgv_admin_overview',[]);assert.equal(updated.restaurants.find(r=>r.id===id).stage,'contracted');assert.equal(updated.activity.length,1);});
await test('Commercial edits reject stale writes and preserve restaurant operations',async()=>{await assert.rejects(rpc('fgv_admin_save_account',[id,0,{stage:'paused'}]),/ha cambiado/);await assert.rejects(rpc('fgv_admin_save_account',[id,1,{stage:'wrong'}]),/fase/);await assert.rejects(rpc('fgv_admin_save_account',[id,1,{stage:'trial',contact_email:'invalid'}]),/correo/);await rpc('fgv_admin_save_account',[id,1,{stage:'paused'}]);assert.equal((await db.query('select active from establishments where id=$1',[id])).rows[0].active,true);assert((await rpc('fgv_list_reservations',[id,date])).length>0);});
await test('Admin creates retry-safe sales workspace without invented tables or client access',async()=>{const key=uuid(),payload={name:'Venta inicial',city:'Sevilla',reservation_type:'digital',reservation_system:'other',email:'sales@example.com',stage:'trial',plan_key:'pro'};const created=await rpc('fgv_admin_create_restaurant',[payload,key]);assert.equal((await rpc('fgv_admin_create_restaurant',[payload,key])).id,created.id);const overview=await rpc('fgv_admin_overview',[]),r=overview.restaurants.find(r=>r.id===created.id);assert.equal(r.plan_key,'pro');assert.equal(r.tables,0);assert.equal(r.has_settings,false);assert.equal(r.stage,'trial');assert.equal((await db.query('select count(*)::int n from establishment_users where establishment_id=$1',[created.id])).rows[0].n,1);});
await test('Invalid admin onboarding rolls back the entire sales workspace',async()=>{const name='Should rollback';await assert.rejects(rpc('fgv_admin_create_restaurant',[{name,reservation_type:'manual',email:'invalid',stage:'trial'},uuid()]),/correo/);assert(!(await rpc('fgv_admin_overview',[])).restaurants.some(r=>r.name===name));await login(null,'anon');await assert.rejects(rpc('fgv_admin_overview',[]),/permission denied/);});

console.log(`${count} integration tests passed`);await db.close();
